apiVersion: v1
kind: Service
metadata:
  name: favicon-public
spec:
  type: NodePort
  selector:
    app: favicon
  ports:
  - port: 4444
    targetPort: 4444
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: favicon
spec:
  replicas: 8
  selector:
    matchLabels:
      app: favicon
  template:
    metadata:
      labels:
        app: favicon
    spec:
      containers:
      - name: favicon
        image: nickblueskylabs/favicon-api
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 4444
        env:
        - name: DB_HOST
          value: cockroachdb-public
        - name: REDIS_HOST
          value: redis